name: Fail Then Pass

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fail-then-pass:
    runs-on: ubuntu-latest

    steps:
      - name: Try to download marker artifact
        uses: actions/download-artifact@v4
        with:
          name: marker
          path: .
        continue-on-error: true

      - name: Determine run status
        id: check
        run: |
          if [ -f first-run.txt ]; then
            echo "Rerun detected. Passing."
            echo "status=pass" >> $GITHUB_OUTPUT
          else
            echo "First run. Failing intentionally."
            echo "marker" > first-run.txt
            echo "status=fail" >> $GITHUB_OUTPUT
          fi

      - name: Upload marker for next run
        if: steps.check.outputs.status == 'fail'
        uses: actions/upload-artifact@v4
        with:
          name: marker
          path: first-run.txt

      - name: Fail intentionally on first run
        if: steps.check.outputs.status == 'fail'
        run: exit 1
