name: Fail then Pass Workflow

on:
  workflow_dispatch:

jobs:
  fail-then-pass:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up run count file
        run: |
          if [ ! -f .run-count ]; then
            echo "0" > .run-count
          fi

      - name: Read run count
        id: read_count
        run: |
          COUNT=$(cat .run-count)
          echo "Current run count: $COUNT"
          echo "count=$COUNT" >> $GITHUB_OUTPUT

      - name: Fail if first run
        if: steps.read_count.outputs.count == '0'
        run: |
          echo "Failing on first run..."
          echo "1" > .run-count
          exit 1

      - name: Success message
        if: steps.read_count.outputs.count == '1'
        run: echo "This is the second run. Success!"

      - name: Commit updated count
        if: always()
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .run-count
          git commit -m "Update run count" || echo "No changes to commit"
          git push || echo "Push failed (likely due to previous failure)"
