name: Fail Then Pass

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fail-then-pass:
    runs-on: ubuntu-latest

    steps:
      - name: Restore first-run marker
        id: cache-restore
        run: |
          if [ -f first-run.txt ]; then
            echo "marker found" > result.txt
          else
            echo "marker not found" > result.txt
        shell: bash

      - name: Check if first run
        id: check
        run: |
          if grep -q "not found" result.txt; then
            echo "First run. Failing intentionally."
            echo "marker" > first-run.txt
            echo "status=fail" >> $GITHUB_OUTPUT
          else
            echo "Rerun detected. Passing."
            echo "status=pass" >> $GITHUB_OUTPUT

      - name: Save marker file
        if: steps.check.outputs.status == 'fail'
        run: |
          echo "Saving marker file..."
          mkdir -p tmp
          cp first-run.txt tmp/
        shell: bash

      - name: Upload marker as artifact
        if: steps.check.outputs.status == 'fail'
        uses: actions/upload-artifact@v4
        with:
          name: marker
          path: tmp/first-run.txt

      - name: Download marker on rerun
        if: steps.check.outputs.status == 'pass'
        uses: actions/download-artifact@v3
        with:
          name: marker
          path: .

      - name: Fail if status is fail
        if: steps.check.outputs.status == 'fail'
        run: exit 1
