name: Fail then Pass Workflow

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  fail-then-pass:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download run count artifact (if exists)
        uses: actions/download-artifact@v4
        with:
          name: run-count-artifact
          path: ./

      - name: Set up run count
        id: setup
        run: |
          if [ -f run-count.txt ]; then
            COUNT=$(cat run-count.txt)
            echo "Run count file found. Count is $COUNT."
          else
            COUNT=0
            echo "No previous run count found. Initializing to 0."
          fi
          echo "run_count=$COUNT" >> $GITHUB_ENV
          echo "$COUNT" > run-count.txt

      - name: Fail if first run
        if: ${{ env.run_count == '0' }}
        run: |
          echo "Failing on first run..."
          echo "1" > run-count.txt  # Update the run count for the next run
          exit 1

      - name: Success message
        if: ${{ env.run_count == '1' }}
        run: |
          echo "This is the second run. Success!"
          echo "0" > run-count.txt  # Reset count to 0 for the next fresh run

      - name: Upload run count artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-count-artifact
          path: run-count.txt
